utils/src/utils.rs
=> [Chore] Remove unused code

liquidity_pool_stableswap/src/storage.rs
=> [Chore] Fix typo

liquidity_pool/src/contract.rs, liquidity_pool/src/test.rs, liquidity_pool_router/src/pool_utils.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/test.rs, liquidity_pool_stableswap/src/token.rs, liquidity_pool_swap_router/src/stableswap_pool.rs, rewards/src/manager.rs
=> [Chore] Remove commented out code

access_control/src/access.rs, liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/test.rs, liquidity_pool_swap_router/src/contract.rs, liquidity_pool_swap_router/src/test.rs
=> [Bugfix] Panic if admin was already set in order to make behavior more explicit

liquidity_pool/src/contract.rs, liquidity_pool_stableswap/src/contract.rs
=> [Chore] Add size check for input vectors

liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/pool_interface.rs, liquidity_pool_router/src/pool_utils.rs, liquidity_pool_router/src/test.rs
This update deletes code relating to the customization of liquidity pools across multiple modules in the liquidity_pool_router. This removal includes functions and tests related to creating and maintaining custom liquidity pools. The complexity of the project is thus somewhat reduced and the focus is now placed on predefined liquidity pool operations.
=> [Bugfix] Remove custom pools

liquidity_pool/src/pool_interface.rs, liquidity_pool_stableswap/src/pool_interface.rs, rewards/src/manager.rs
=> [Chore] Todo's cleanup

liquidity_pool/src/contract.rs, liquidity_pool/src/pool_interface.rs, liquidity_pool/src/test.rs, liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/pool_interface.rs, liquidity_pool_router/src/test.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/pool_interface.rs, liquidity_pool_stableswap/src/test.rs
=> [Feature] Check minimum minted amount on deposit

liquidity_pool/src/contract.rs, liquidity_pool/src/pool_interface.rs, liquidity_pool/src/test.rs, liquidity_pool/src/testutils.rs, liquidity_pool_router/src/pool_utils.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/pool_interface.rs, liquidity_pool_stableswap/src/test.rs, rewards/src/manager.rs, rewards/src/storage.rs
Audit MI-05
Removed the reward storage address from the rewards configuration to simplify reward management. Improved token deposit, swap, and withdraw methods for more straightforward and deterministic transaction authorization.
=> [Feature] Update rewards configuration and token transactions

.github/workflows/rust.yml, liquidity_pool/src/test.rs, liquidity_pool/src/testutils.rs, liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/test.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/test.rs
=> [Feature] Update rewards configuration and token transactions #2

liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/test.rs
=> [Bugfix] Address remove liquidity imbalance race condition

liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/pool_utils.rs, liquidity_pool_router/src/storage.rs, liquidity_pool_router/src/test.rs
fix pool reinitialization issue - after removal it was impossible to create new with same parameters
=> [Bugfix] Pool recreation fix

liquidity_pool/src/contract.rs, liquidity_pool/src/test.rs, liquidity_pool_stableswap/src/test.rs
When user deposits zero amount of token pools accepts it, but then burns all funds sent on swap
=> [Bugfix] Fix zero initial deposit

liquidity_pool/src/contract.rs, liquidity_pool/src/pool_interface.rs, liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/pool_interface.rs, liquidity_pool_router/src/test.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/pool_interface.rs
add method to retrieve total amount of shares minted by pool
=> [Feature] Total shares getter

liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/errors.rs, liquidity_pool_router/src/pool_utils.rs, liquidity_pool_router/src/router_interface.rs, liquidity_pool_router/src/storage.rs, liquidity_pool_router/src/test.rs, liquidity_pool_stableswap/Cargo.toml, liquidity_pool_stableswap/Taskfile.yaml, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/lib.rs, liquidity_pool_stableswap/src/pool_2_constants.rs, liquidity_pool_stableswap/src/pool_3_constants.rs, liquidity_pool_stableswap/src/pool_4_constants.rs, liquidity_pool_stableswap/src/pool_constants.rs, liquidity_pool_stableswap/src/storage.rs, liquidity_pool_stableswap/src/test.rs
revamp stableswap compilation - remove all features, make n_tokens dynamic since we always can get it from tokens size
=> [Chore] Stableswap build change

token/src/allowance.rs
(cherry picked from commit b16dfc3338f3248b1b0a54b8bd769a3df3e84d3d)
audit copy of #44
=> [Bugfix] fix zero allowance

liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/pool_constants.rs, liquidity_pool_stableswap/src/pool_interface.rs, liquidity_pool_swap_router/src/stableswap_pool.rs
remove unused functions and get rid of unnecessary constants
=> [Chore] Stableswap cleanup

Cargo.lock, Cargo.toml, liquidity_pool/Cargo.toml, liquidity_pool/src/contract.rs, liquidity_pool/src/pool.rs, liquidity_pool/src/test.rs, liquidity_pool_events/Cargo.toml, liquidity_pool_events/src/lib.rs, liquidity_pool_stableswap/Cargo.toml, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/pool_interface.rs, liquidity_pool_stableswap/src/test.rs
add pool level events to track trades: deposit_liquidity, trade, withdraw_liquidity
=> [Feature] Implement pool level statistic events

access_control/src/errors.rs, liquidity_pool/src/contract.rs, liquidity_pool/src/errors.rs, liquidity_pool/src/test.rs, liquidity_pool/src/testutils.rs, liquidity_pool_router/src/errors.rs, liquidity_pool_router/src/storage.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/errors.rs, liquidity_pool_validation_errors/src/lib.rs, rewards/src/errors.rs, rewards/src/lib.rs, rewards/src/manager.rs, rewards/src/storage.rs, token/src/errors.rs, utils/src/storage_errors.rs
change invariant aggregation logic to update pages each time rather then when the last cell is closed
=> [Bugfix] Optimize storage keys usage for rewards to avoid budget exceed error

liquidity_pool_router/src/constants.rs, liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/pool_interface.rs, liquidity_pool_router/src/router_interface.rs, liquidity_pool_router/src/storage.rs, liquidity_pool_router/src/test.rs
configure pool creation fee separately for constant product & stableswap;
create stableswap pools with default `A` = 1500
=> [Improvement] improve pool creation flow

fees_collector/src/contract.rs, liquidity_pool/src/contract.rs, liquidity_pool/src/test.rs, liquidity_pool/src/testutils.rs, liquidity_pool/src/token.rs, liquidity_pool_liquidity_calculator/src/contract.rs, liquidity_pool_plane/src/contract.rs, liquidity_pool_router/src/contract.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/test.rs, liquidity_pool_swap_router/src/contract.rs
fix constant product pool issue causing reward token withdrawal if it's one of the pool tokens
=> [Bugfix] fix reward token withdrawal

liquidity_pool/src/contract.rs, liquidity_pool/src/test.rs, liquidity_pool_events/src/lib.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/test.rs
add events for killswitches to listen to
=> [Feature] emit killswitch events

liquidity_pool/src/contract.rs, liquidity_pool/src/test.rs
fix deposit error caused by typo
=> [Bugfix] fix wrong pool reserves on deposit

access_control/src/access.rs, access_control/src/errors.rs, liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/pool_interface.rs, liquidity_pool_router/src/router_interface.rs, liquidity_pool_router/src/storage.rs, liquidity_pool_router/src/test.rs
add operator role for better rewards distribution automation
=> [Feature] add operator role to router contract

liquidity_pool_liquidity_calculator/src/calculator.rs, liquidity_pool_liquidity_calculator/src/contract.rs, liquidity_pool_liquidity_calculator/src/stableswap_pool.rs
- [ x ] pre-calculate stableswap variables during liquidity calculation
=> [Feature] Optimize liquidity calculation operations amount #1

liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/errors.rs
don't return solution if no convergence happens during newton method iterations
=> [Bugfix] H02 numerical stability checks

liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/token.rs
use tokens to generate pool LP token salt
=> [Chore] l04 empty salt

liquidity_pool_liquidity_calculator/src/errors.rs, liquidity_pool_liquidity_calculator/src/lib.rs, liquidity_pool_liquidity_calculator/src/stableswap_pool.rs
#94 
add similar checks to liquidity calculator
=> [Bugfix] H02 numerical stability checks 2

liquidity_pool/src/contract.rs, liquidity_pool/src/pool_interface.rs, liquidity_pool/src/test.rs, liquidity_pool/src/testutils.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/pool_interface.rs, liquidity_pool_stableswap/src/test.rs, liquidity_pool_stableswap/src/testutils.rs
depends on #100 
return reward surplus from pool to router. may happen on pool reward re-configuration with less value than before
=> [Feature] Return unused reward to router

access_control/src/access.rs, access_control/src/events.rs, access_control/src/lib.rs, fees_collector/src/contract.rs, fees_collector/src/test.rs, liquidity_pool/src/contract.rs, liquidity_pool/src/test.rs, liquidity_pool_liquidity_calculator/src/contract.rs, liquidity_pool_liquidity_calculator/src/test.rs, liquidity_pool_plane/src/contract.rs, liquidity_pool_plane/src/test.rs, liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/test.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/events.rs, liquidity_pool_stableswap/src/lib.rs, liquidity_pool_stableswap/src/test.rs, rewards/src/events.rs, rewards/src/lib.rs, token/src/contract.rs, token/src/test.rs
Add admin events for: ownership transfer, ramp a, change fee, update privileged addrs, config rewards
=> [Feature] L07 Add admin events

liquidity_pool/src/contract.rs, liquidity_pool/src/test.rs, liquidity_pool_events/src/lib.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/test.rs, rewards/src/events.rs
Add missing pool events:
- `claim_reward` for pool claim method
- `withdraw_liquidity` for stableswap pool remove_liquidity_imbalance method
=> [Bugfix] Add missing pool events

liquidity_pool_router/src/constants.rs, liquidity_pool_router/src/contract.rs, liquidity_pool_router/src/pool_utils.rs, liquidity_pool_router/src/test.rs, liquidity_pool_stableswap/src/contract.rs, liquidity_pool_stableswap/src/pool_interface.rs
document stored amplification factor as `Amp = A*N**(N-1)`
calculate stableswap initialization amp depending on tokens amount
=> Document amp
